version: "3"
services:
    keycloak:
        build: ./keycloak
        image: hoivakoti/keycloak:latest
        environment:
            KEYCLOAK_USER: "admin"
            DB_USER: "postgres"
            DB_PASSWORD: "postgres"
            DB_ADDR: "postgres"
            KEYCLOAK_PASSWORD: "admin"
            KEYCLOAK_IMPORT: "/keycloak/hoivakodit-realm.json"
            DB_VENDOR: "POSTGRES"
            DB_DATABASE: "postgres"
            DB_SCHEMA: "public"
            PROXY_ADDRESS_FORWARDING: "true"
            KEYCLOAK_FRONTEND_URL: "http://localhost:4000/auth"
        volumes:
            - ./keycloak/hoivakodit-realm.json:/keycloak/hoivakodit-realm.json
        depends_on:
            - postgres
        networks:
            - hoivakodit-network
