version: "3"
services:
    keycloak:
        image: quay.io/keycloak/keycloak:latest
        environment:
            DB_VENDOR: POSTGRES
            DB_ADDR: postgres
            DB_DATABASE: postgres
            DB_USER: postgres
            DB_SCHEMA: public
            DB_PASSWORD: postgres
            REALM: hoivakodit
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
            KEYCLOAK_FRONTEND_URL: "http://localhost:5000/auth"
            PROXY_ADDRESS_FORWARDING: "true"
        depends_on:
            - postgres
            - backend
        networks:
            - hoivakodit-network

    auth-proxy:
        image: nginx:1.19-alpine
        ports:
            - 5000:5000
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - backend
            - keycloak
        networks:
            - hoivakodit-network
