version: "3"
services:
    keycloak:
        image: quay.io/keycloak/keycloak:11.0.3
        environment:
            DB_VENDOR: POSTGRES
            DB_ADDR: postgres
            DB_DATABASE: postgres
            DB_USER: postgres
            DB_SCHEMA: public
            DB_PASSWORD: postgres
            REALM: hoivakodit
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: "${ADMIN_PASSWORD}"
            PROXY_ADDRESS_FORWARDING: "true"
        depends_on:
            - postgres
        networks:
            - hoivakodit-network

    auth-proxy:
        image: nginx:1.19-alpine
        ports:
            - 4000:8080
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - hoivakodit-network
