jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          working_directory:  ~/project/backend
          command: yarn install
        
      - run:
          working_directory:  ~/project/backend
          command: yarn test
      - run:
          working_directory:  ~/project/frontend-react
          command: yarn install
        
      - run:
          working_directory:  ~/project/frontend-react
          command: yarn test
workflows:
  version: 2
  build_and_test:
    jobs: