export interface NursingHome{
	name: string,
	owner: string,
	address: string,
	ara?: boolean,
	www?: string,
	apartment_count?: number,
	language?: string,
	lah?: boolean,
	summary?: string,
	postal_code: string,
	city: string,
	arrival_guide_public_transit?: string,
	arrival_guide_car?: string,
	construction_year?: number,
	building_info?: string,
	apartments_have_bathroom?: boolean,
	apartment_count_info?: string,
	apartment_square_meters?: number,
	rent?: number,
	rent_info?: string,
	language_info?: string,
	menu_link?: string,
	meals_preparation?: string,
	meals_info?: string,
	activities_info?: string,
	activities_link?: string,
	outdoors_possibilities_info?: string,
	outdoors_possibilities_link?: string,
	tour_info?: string,
	contact_name?: string,
	contact_title?: string,
	contact_phone?: string,
	contact_phone_info?: string,
	email?: string,
	accessibility_info?: string,
	staff_info?: string,
	staff_satisfaction_info?: string,
	other_services?: string,
	nearby_services?: string
}

export const nursing_home_columns_info:any = [
{csv: "", sql: "id", type: "uuid"},
{csv: "Hoivakodin nimi", sql: "name", type: "string"},
{csv: "Omistajan nimi", sql: "owner", type: "string"},
{csv: "Käyntiosoite", sql: "address", type: "string"},
{csv: "ARA-kohde", sql: "ara", type: "boolean"},
{csv: "Verkkosivujen osoite", sql: "www", type: "string"},
{csv: "Asuntojen määrä", sql: "apartment_count", type: "integer"},
{csv: "Palvelukieli", sql: "language", type: "string"},
{csv: "Lyhytaikaisen hoivan asuntoja", sql: "lah", type: "boolean"},
{csv: "Tiivistelmä", sql: "summary", type: "string"},
{csv: "Postinumero", sql: "postal_code", type: "string"},
{csv: "Kaupunki", sql: "city", type: "string"},
{csv: "Saapumisohjeet (julkiset kulkuvälineet)", sql: "arrival_guide_public_transit", type: "string"},
{csv: "Saapumisohjeet (autolla saavuttaessa)", sql: "arrival_guide_car", type: "string"},
{csv: "Rakennusvuosi", sql: "construction_year", type: "integer"},
{csv: "Lisätietoja rakennuksesta", sql: "building_info", type: "string"},
{csv: "Onko kaikissa asunnoissa oma kylpyhuone", sql: "apartments_have_bathroom", type: "boolean"},
{csv: "Lisätietoja asuntojen määrästä", sql: "apartment_count_info", type: "string"},
{csv: "Asuntojen neliömäärä", sql: "apartment_square_meters", type: "float"},
{csv: "Vuokra", sql: "rent", type: "float"},
{csv: "Lisätietoja vuokrasta", sql: "rent_info", type: "string"},
{csv: "Palvelukielen lisätietoja", sql: "language_info", type: "string"},
{csv: "Linkki ruokalistaan", sql: "menu_link", type: "string"},
{csv: "Ruoan valmistus", sql: "meals_preparation", type: "string"},
{csv: "Lisätietoa ruoasta", sql: "meals_info", type: "string"},
{csv: "Kuvaus hoivakodissa järjestettävästä toiminnasta", sql: "activities_info", type: "string"},
{csv: "Linkki toimintakalenteriin", sql: "activities_link", type: "string"},
{csv: "Kuvaus hoivakodin ulkoilumahdollisuuksista", sql: "outdoors_possibilities_info", type: "string"},
{csv: "Linkki lisätietoihin ulkoilumahdollisuuksista", sql: "outdoors_possibilities_link", type: "string"},
{csv: "Vapaa kuvaus hoivakotiin tutustumisesta", sql: "tour_info", type: "string"},
{csv: "Yhteyshenkilö", sql: "contact_name", type: "string"},
{csv: "Yhteyshenkilön tehtävänimike", sql: "contact_title", type: "string"},
{csv: "Puhelinnumero", sql: "contact_phone", type: "string"},
{csv: "Puhelinnumeron lisätietoja", sql: "contact_phone_info", type: "string"},
{csv: "Sähköposti", sql: "email", type: "string"},
{csv: "Tietoja esteettömyydestä", sql: "accessibility_info", type: "string"},
{csv: "Henkilöstö", sql: "staff_info", type: "string"},
{csv: "Lisätietoa henkilöstön tyytyväisyydestä", sql: "staff_satisfaction_info", type: "string"},
{csv: "Muut hoivakodin palvelut", sql: "other_services", type: "string"},
{csv: "Lähellä olevat palvelut", sql: "nearby_services", type: "string"},
]